######################################################################
# Automatically generated by qmake (2.00a) Sun Jan 8 21:18:26 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ringwidget.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp ringwidget.cpp blockstore.cpp block.cpp \
  storage.cpp prefs.cpp line.cpp

QT += xml
QT += qt3support

VERSION = -0.1
